
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhahxzsenmhdtgmltrjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoYWh4enNlbm1oZHRnbWx0cmpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjU3ODUsImV4cCI6MjA2MjQ0MTc4NX0.Se3lpJxv8wrKMluLWGtFMIxtwDjS8ZAFAtMOb12TjFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
